spring.datasource.url=jdbc:mysql://localhost:3306/quickserve_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081

jwt.secret=9a67475d459146e4ad2f0274bc05ecb2a67475d459146e4ad2f0274bc05ecb2
jwt.expiration=86400000
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG