spring.application.name=quickserve-backend

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/quickserve_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

razorpay.key.id=rzp_test_SSmEV6mCKeKm8A
razorpay.key.secret=rJtcC0Jo03paKMT7tgk6Fttw

jwt.secret=MySuperSecretKeyForQuickServeProject123456789012345
jwt.expiration=86400000